services:
  backend:
    image: reinsaemani/inventory-backend:v1.0.5
    container_name: inventory-backend
    ports:
      - "5051:5051"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    command: pnpm start

  mysql:
    image: mysql:8.4
    container_name: inventory-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u test -ptest"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
